# Generated by Custom Synthesis Engine — SDC for OpenLane
# Target: SKY130

create_clock -name clk -period 5.30 [get_ports {clk}]

set_clock_uncertainty 0.250 [get_clocks {clk}]

set_input_delay 1.00 -clock [get_clocks {clk}] [all_inputs]
set_output_delay 1.00 -clock [get_clocks {clk}] [all_outputs]

set_max_fanout 10 [current_design]
set_max_transition 1.5 [current_design]
set_load 0.05 [all_outputs]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin Y [all_inputs]
